In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("keremkarayaz/coffee-shop-sales")

print("Path to dataset files:", path)

Downloading from https://www.kaggle.com/api/v1/datasets/download/keremkarayaz/coffee-shop-sales?dataset_version_number=1...

100%|██████████| 8.23M/8.23M [00:00<00:00, 56.8MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/keremkarayaz/coffee-shop-sales/versions/1

In [5]:
# Load data
import pandas as pd

df = pd.read_excel(path + "/Coffee Shop Sales.xlsx", sheet_name="Transactions")
df

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
0,1,2023-01-01,07:06:11,2,5,Lower Manhattan,32,3.00,Coffee,Gourmet brewed coffee,Ethiopia Rg
1,2,2023-01-01,07:08:56,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
2,3,2023-01-01,07:14:04,2,5,Lower Manhattan,59,4.50,Drinking Chocolate,Hot chocolate,Dark chocolate Lg
3,4,2023-01-01,07:20:24,1,5,Lower Manhattan,22,2.00,Coffee,Drip coffee,Our Old Time Diner Blend Sm
4,5,2023-01-01,07:22:41,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
...,...,...,...,...,...,...,...,...,...,...,...
149111,149452,2023-06-30,20:18:41,2,8,Hell's Kitchen,44,2.50,Tea,Brewed herbal tea,Peppermint Rg
149112,149453,2023-06-30,20:25:10,2,8,Hell's Kitchen,49,3.00,Tea,Brewed Black tea,English Breakfast Lg
149113,149454,2023-06-30,20:31:34,1,8,Hell's Kitchen,45,3.00,Tea,Brewed herbal tea,Peppermint Lg
149114,149455,2023-06-30,20:57:19,1,8,Hell's Kitchen,40,3.75,Coffee,Barista Espresso,Cappuccino
149115,149456,2023-06-30,20:57:19,2,8,Hell's Kitchen,64,0.80,Flavours,Regular syrup,Hazelnut syrup

In [8]:
# Check Null Values
df.isnull().sum()

transaction_id      0
transaction_date    0
transaction_time    0
transaction_qty     0
store_id            0
store_location      0
product_id          0
unit_price          0
product_category    0
product_type        0
product_detail      0
dtype: int64

In [9]:
# Check Duplicated value
df.duplicated().sum()

np.int64(0)

In [11]:
# Transformations
# Convert Transaction Date

df['Date'] = pd.to_datetime(df['transaction_date'])
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day

In [13]:
# 6. Convert Transaction Time to datetime & extract

df['Time'] = pd.to_datetime(df['transaction_time'].astype(str))
df['Hour'] = df['Time'].dt.hour
df['Minute'] = df['Time'].dt.minute

/tmp/ipython-input-1871261185.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Time'] = pd.to_datetime(df['transaction_time'].astype(str))

In [14]:
df

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail,Date,Year,Month,Day,Time,Hour,Minute
0,1,2023-01-01,07:06:11,2,5,Lower Manhattan,32,3.00,Coffee,Gourmet brewed coffee,Ethiopia Rg,2023-01-01,2023,1,1,2025-09-15 07:06:11,7,6
1,2,2023-01-01,07:08:56,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,2023-01-01,2023,1,1,2025-09-15 07:08:56,7,8
2,3,2023-01-01,07:14:04,2,5,Lower Manhattan,59,4.50,Drinking Chocolate,Hot chocolate,Dark chocolate Lg,2023-01-01,2023,1,1,2025-09-15 07:14:04,7,14
3,4,2023-01-01,07:20:24,1,5,Lower Manhattan,22,2.00,Coffee,Drip coffee,Our Old Time Diner Blend Sm,2023-01-01,2023,1,1,2025-09-15 07:20:24,7,20
4,5,2023-01-01,07:22:41,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,2023-01-01,2023,1,1,2025-09-15 07:22:41,7,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149111,149452,2023-06-30,20:18:41,2,8,Hell's Kitchen,44,2.50,Tea,Brewed herbal tea,Peppermint Rg,2023-06-30,2023,6,30,2025-09-15 20:18:41,20,18
149112,149453,2023-06-30,20:25:10,2,8,Hell's Kitchen,49,3.00,Tea,Brewed Black tea,English Breakfast Lg,2023-06-30,2023,6,30,2025-09-15 20:25:10,20,25
149113,149454,2023-06-30,20:31:34,1,8,Hell's Kitchen,45,3.00,Tea,Brewed herbal tea,Peppermint Lg,2023-06-30,2023,6,30,2025-09-15 20:31:34,20,31
149114,149455,2023-06-30,20:57:19,1,8,Hell's Kitchen,40,3.75,Coffee,Barista Espresso,Cappuccino,2023-06-30,2023,6,30,2025-09-15 20:57:19,20,57
149115,149456,2023-06-30,20:57:19,2,8,Hell's Kitchen,64,0.80,Flavours,Regular syrup,Hazelnut syrup,2023-06-30,2023,6,30,2025-09-15 20:57:19,20,57

In [19]:
# ===== Transform Categorical Columns to Numeric =====
# product_category mapping
category_map = {
    "Coffee": 1,
    "Tea": 2,
    "Bakery": 3,
    "Drinking Chocolate": 4,
    "Flavours": 5
}
df["product_category_num"] = df["product_category"].map(category_map)

In [20]:
# store_location mapping
location_map = {
    "Hell's Kitchen": 1,
    "Astoria": 2,
    "Lower Manhattan": 3
}
df["store_location_num"] = df["store_location"].map(location_map)

In [24]:
# product_type mapping
product_type_map = {
    "Brewed Chai tea": 1,
    "Gourmet brewed coffee": 2,
    "Barista Espresso": 3,
    "Hot chocolate": 4,
    "Brewed Black tea": 5,
    "Drip coffee" : 6
}
df["product_type_num"] = df["product_type"].map(product_type_map)

In [25]:
# Show transformed data
print(df[["product_category","product_category_num",
          "store_location","store_location_num",
          "product_type","product_type_num"]].head())

     product_category  product_category_num   store_location  \
0              Coffee                   1.0  Lower Manhattan
1                 Tea                   2.0  Lower Manhattan
2  Drinking Chocolate                   4.0  Lower Manhattan
3              Coffee                   1.0  Lower Manhattan
4                 Tea                   2.0  Lower Manhattan

   store_location_num           product_type  product_type_num
0                   3  Gourmet brewed coffee               2.0
1                   3        Brewed Chai tea               1.0
2                   3          Hot chocolate               4.0
3                   3            Drip coffee               6.0
4                   3        Brewed Chai tea               1.0

In [27]:
df["product_category_num"] = df["product_category_num"].fillna(0).astype(int)
df["store_location_num"] = df["store_location_num"].fillna(0).astype(int)
df["product_type_num"] = df["product_type_num"].fillna(0).astype(int)

In [28]:
print(df[["product_category","product_category_num",
          "store_location","store_location_num",
          "product_type","product_type_num"]].head())

     product_category  product_category_num   store_location  \
0              Coffee                     1  Lower Manhattan
1                 Tea                     2  Lower Manhattan
2  Drinking Chocolate                     4  Lower Manhattan
3              Coffee                     1  Lower Manhattan
4                 Tea                     2  Lower Manhattan

   store_location_num           product_type  product_type_num
0                   3  Gourmet brewed coffee                 2
1                   3        Brewed Chai tea                 1
2                   3          Hot chocolate                 4
3                   3            Drip coffee                 6
4                   3        Brewed Chai tea                 1

In [29]:
# Total Amount

df['total_amount'] = df['transaction_qty'] * df['unit_price']

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149116 entries, 0 to 149115
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   transaction_id        149116 non-null  int64
 1   transaction_date      149116 non-null  datetime64[ns]
 2   transaction_time      149116 non-null  object
 3   transaction_qty       149116 non-null  int64
 4   store_id              149116 non-null  int64
 5   store_location        149116 non-null  object
 6   product_id            149116 non-null  int64
 7   unit_price            149116 non-null  float64
 8   product_category      149116 non-null  object
 9   product_type          149116 non-null  object
 10  product_detail        149116 non-null  object
 11  Date                  149116 non-null  datetime64[ns]
 12  Year                  149116 non-null  int32
 13  Month                 149116 non-null  int32
 14  Day                   149116 non-null  int32
 15  Time                  149116 non-null  datetime64[ns]
 16  Hour                  149116 non-null  int32
 17  Minute                149116 non-null  int32
 18  product_category_num  149116 non-null  int64
 19  store_location_num    149116 non-null  int64
 20  product_type_num      149116 non-null  int64
 21  total_amount          149116 non-null  float64
dtypes: datetime64[ns](3), float64(2), int32(5), int64(7), object(5)
memory usage: 22.2+ MB

In [31]:
df

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,...,Year,Month,Day,Time,Hour,Minute,product_category_num,store_location_num,product_type_num,total_amount
0,1,2023-01-01,07:06:11,2,5,Lower Manhattan,32,3.00,Coffee,Gourmet brewed coffee,...,2023,1,1,2025-09-15 07:06:11,7,6,1,3,2,6.00
1,2,2023-01-01,07:08:56,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,...,2023,1,1,2025-09-15 07:08:56,7,8,2,3,1,6.20
2,3,2023-01-01,07:14:04,2,5,Lower Manhattan,59,4.50,Drinking Chocolate,Hot chocolate,...,2023,1,1,2025-09-15 07:14:04,7,14,4,3,4,9.00
3,4,2023-01-01,07:20:24,1,5,Lower Manhattan,22,2.00,Coffee,Drip coffee,...,2023,1,1,2025-09-15 07:20:24,7,20,1,3,6,2.00
4,5,2023-01-01,07:22:41,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,...,2023,1,1,2025-09-15 07:22:41,7,22,2,3,1,6.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149111,149452,2023-06-30,20:18:41,2,8,Hell's Kitchen,44,2.50,Tea,Brewed herbal tea,...,2023,6,30,2025-09-15 20:18:41,20,18,2,1,0,5.00
149112,149453,2023-06-30,20:25:10,2,8,Hell's Kitchen,49,3.00,Tea,Brewed Black tea,...,2023,6,30,2025-09-15 20:25:10,20,25,2,1,5,6.00
149113,149454,2023-06-30,20:31:34,1,8,Hell's Kitchen,45,3.00,Tea,Brewed herbal tea,...,2023,6,30,2025-09-15 20:31:34,20,31,2,1,0,3.00
149114,149455,2023-06-30,20:57:19,1,8,Hell's Kitchen,40,3.75,Coffee,Barista Espresso,...,2023,6,30,2025-09-15 20:57:19,20,57,1,1,3,3.75
149115,149456,2023-06-30,20:57:19,2,8,Hell's Kitchen,64,0.80,Flavours,Regular syrup,...,2023,6,30,2025-09-15 20:57:19,20,57,5,1,0,1.60

**Star Schema**

In [32]:
# Date Dimension
dim_date = df[['transaction_date','Date','Year','Month','Day','Hour','Minute']].drop_duplicates().reset_index(drop=True)
dim_date['Date_Key'] = range(1, len(dim_date) + 1)

In [33]:
# Store Dimension
dim_store = df[['store_id','store_location','store_location_num']].drop_duplicates().reset_index(drop=True)
dim_store['Store_Key'] = range(1, len(dim_store) + 1)

In [34]:
# Product Dimension
dim_product = df[['product_id','product_category','product_category_num','product_type','product_type_num']].drop_duplicates().reset_index(drop=True)
dim_product['Product_Key'] = range(1, len(dim_product) + 1)

In [35]:
# (Fact table )
fact_transactions = df[['transaction_id','store_id','product_id','Date','transaction_qty','unit_price','total_amount','product_id']].copy()
fact_transactions['Transaction_Key'] = range(1, len(fact_transactions) + 1)

In [36]:
# Save Them As CSV Files
fact_transactions.to_csv("fact_transactions.csv",index=False)
dim_date.to_csv("dim_date.csv",index=False)
dim_product.to_csv("dim_product.csv",index=False)
dim_store.to_csv("dim_store.csv",index=False)

In [38]:
#Download
from google.colab import files
for file in ["fact_transactions.csv", "dim_date.csv", "dim_product.csv", "dim_store.csv"]:
    files.download(file)